---

- name: Solr | OS Tunning
  import_tasks: os-tunning.yml
  tags:
    - prometheus_solr_exporter_tunning
  when: prometheus_solr_exporter_os_tunning

- name: SOLR_EXPORTER | Install
  import_tasks: install.yml
  tags:
    - prometheus_solr_exporter_install

- name: SOLR_EXPORTER | Config
  import_tasks: config.yml
  tags:
    - prometheus_solr_exporter_config

- name: SOLR_EXPORTER | Service
  import_tasks: service.yml
  tags:
    - prometheus_solr_exporter_service
