---
- name: SOLR_EXPORTER | Copying service definition
  template:
    src: "{{ prometheus_solr_exporter_service_file }}"
    dest: "{{ prometheus_solr_exporter_service_location }}"
    owner: root
    group: root
    mode: 0644
  notify: restart solr_exporter

- name: SOLR_EXPORTER | Enabling service daemon
  systemd:
    name: "{{ prometheus_solr_exporter_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
